"""added trade type to option tranining labels pk

Revision ID: 34e4b32504b0
Revises: 97ce5a9c21aa
Create Date: 2017-12-02 18:01:23.160177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e4b32504b0'
down_revision = '97ce5a9c21aa'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    connection.execute("ALTER TABLE option_training_labels DROP CONSTRAINT option_training_labels_pkey")
    connection.execute("ALTER TABLE option_training_labels ADD PRIMARY KEY (ticker, experiation_date, strike, trade_date, trade_type)")
    
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()
    connection.execute("ALTER TABLE option_training_labels DROP CONSTRAINT option_training_labels_pkey")
    connection.execute("ALTER TABLE option_training_labels ADD PRIMARY KEY (ticker, experiation_date, strike, trade_date)")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
