"""change option forward prices table from min to max for put prices

Revision ID: 59a595d7a506
Revises: c6318ad72941
Create Date: 2018-02-01 19:33:14.133695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59a595d7a506'
down_revision = 'c6318ad72941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_forward_prices', sa.Column('max_forward_put_ask_price', sa.Float(), nullable=False))
    op.add_column('option_forward_prices', sa.Column('max_forward_put_bid_price', sa.Float(), nullable=False))
    op.drop_column('option_forward_prices', 'min_forward_put_ask_price')
    op.drop_column('option_forward_prices', 'min_forward_put_bid_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_forward_prices', sa.Column('min_forward_put_bid_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('option_forward_prices', sa.Column('min_forward_put_ask_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('option_forward_prices', 'max_forward_put_bid_price')
    op.drop_column('option_forward_prices', 'max_forward_put_ask_price')
    # ### end Alembic commands ###
