"""Create table for option training labels

Revision ID: 97ce5a9c21aa
Revises: e3bddea6011c
Create Date: 2017-11-21 20:12:29.492359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ce5a9c21aa'
down_revision = 'e3bddea6011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_training_labels',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('experiation_date', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trade_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'experiation_date', 'strike', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_training_labels')
    # ### end Alembic commands ###
