"""Change equity historical integers to bigint datatype

Revision ID: bbf14b8a2ae0
Revises: cdabf89ce28b
Create Date: 2017-11-06 19:26:56.192773

"""
from alembic import op
import sqlalchemy as sa
from app import db


# revision identifiers, used by Alembic.
revision = 'bbf14b8a2ae0'
down_revision = 'cdabf89ce28b'
branch_labels = None
depends_on = None


def upgrade():
    connection = op.get_bind()
    connection.execute("ALTER TABLE equity_historical ALTER COLUMN volume TYPE BIGINT USING volume::bigint")
    connection.execute("ALTER TABLE equity_historical ALTER COLUMN adj_volume TYPE BIGINT USING adj_volume::bigint")
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade():
    connection = op.get_bind()
    connection.execute("ALTER TABLE equity_historical ALTER COLUMN volume TYPE INT USING volume::integer")
    connection.execute("ALTER TABLE equity_historical ALTER COLUMN adj_volume TYPE INT USING adj_volume::integer")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
