"""added option forward volatilities table

Revision ID: c193388f6e1f
Revises: 59a595d7a506
Create Date: 2018-02-26 11:44:35.205952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c193388f6e1f'
down_revision = '59a595d7a506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_forward_volatilities',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('experiation_date', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('forward_volatility', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'experiation_date', 'strike', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_forward_volatilities')
    # ### end Alembic commands ###
