"""added volatilites for call/put and bid/ask prices rather than only one volatility

Revision ID: c42be115a6f1
Revises: c193388f6e1f
Create Date: 2018-02-26 16:14:50.443931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c42be115a6f1'
down_revision = 'c193388f6e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_forward_volatilities', sa.Column('forward_call_ask_volatility', sa.Float(), nullable=False))
    op.add_column('option_forward_volatilities', sa.Column('forward_call_bid_volatility', sa.Float(), nullable=False))
    op.add_column('option_forward_volatilities', sa.Column('forward_put_ask_volatility', sa.Float(), nullable=False))
    op.add_column('option_forward_volatilities', sa.Column('forward_put_bid_volatility', sa.Float(), nullable=False))
    op.drop_column('option_forward_volatilities', 'forward_volatility')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_forward_volatilities', sa.Column('forward_volatility', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('option_forward_volatilities', 'forward_put_bid_volatility')
    op.drop_column('option_forward_volatilities', 'forward_put_ask_volatility')
    op.drop_column('option_forward_volatilities', 'forward_call_bid_volatility')
    op.drop_column('option_forward_volatilities', 'forward_call_ask_volatility')
    # ### end Alembic commands ###
