"""add option forward prices table

Revision ID: c6318ad72941
Revises: 34e4b32504b0
Create Date: 2018-02-01 15:25:43.014433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6318ad72941'
down_revision = '34e4b32504b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_forward_prices',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('experiation_date', sa.Date(), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('max_forward_call_bid_price', sa.Float(), nullable=False),
    sa.Column('max_forward_call_ask_price', sa.Float(), nullable=False),
    sa.Column('min_forward_put_bid_price', sa.Float(), nullable=False),
    sa.Column('min_forward_put_ask_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'experiation_date', 'strike', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_forward_prices')
    # ### end Alembic commands ###
