"""Create equity volatilities table

Revision ID: cdabf89ce28b
Revises: fcde47473793
Create Date: 2017-11-06 17:57:40.423393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdabf89ce28b'
down_revision = 'fcde47473793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_volatilities',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ma_10', sa.Float(), nullable=False),
    sa.Column('ma_50', sa.Float(), nullable=False),
    sa.Column('ma_100', sa.Float(), nullable=False),
    sa.Column('ma_250', sa.Float(), nullable=False),
    sa.Column('ma_lifetime', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equity_volatilities')
    # ### end Alembic commands ###
