"""drop ma_lifetime column for equity_volatilities table

Revision ID: e3bddea6011c
Revises: bbf14b8a2ae0
Create Date: 2017-11-07 19:46:11.462464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3bddea6011c'
down_revision = 'bbf14b8a2ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equity_volatilities', 'ma_lifetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_volatilities', sa.Column('ma_lifetime', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
